version: "2"

services:
  nginx:
      #image: blacklabelops/nginx
      build:
        context: .
        dockerfile: Dockerfile-nginx
      container_name: nginx_server
      ports:
        - '443:443'
        - '80:80'
      volumes:
        - ./volumes/nginx_volume:/home/nginx
        - /etc/letsencrypt:/etc/letsencrypt
        #- letsencrypt_challenges:/var/www/letsencrypt
      environment:
        - 'SERVER1SERVER_NAME=keycloak.nellmedina.com'
        - 'SERVER1REVERSE_PROXY_LOCATION1=/'
        - 'SERVER1REVERSE_PROXY_PASS1=http://keycloak:8080/'
        - 'SERVER1HTTPS_ENABLED=true'
        - 'SERVER1HTTP_ENABLED=true'
        - 'SERVER1LETSENCRYPT_CERTIFICATES=true'
        - 'SERVER1CERTIFICATE_FILE=/etc/letsencrypt/live/keycloak.syntelli.com/fullchain.pem'
        - 'SERVER1CERTIFICATE_KEY=/etc/letsencrypt/live/keycloak.syntelli.com/privkey.pem'
        - 'SERVER1CERTIFICATE_TRUSTED=/etc/letsencrypt/live/keycloak.syntelli.com/fullchain.pem'
        - 'SERVER1PROXY_APPLICATION=keycloak'
      restart: unless-stopped
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: unless-stopped
      ports:
          - "15432:15432"
      environment:
          - POSTGRES_DB=keycloak
          - POSTGRES_USER=keycloak
          - POSTGRES_PASSWORD=keycloak
          - POSTGRES_ROOT_PASSWORD=keycloak
      volumes:
        - keycloak_postgresql_volume:/var/lib/postgresql/data
      restart: unless-stopped
  keycloak:
      image: jboss/keycloak
      container_name: keycloak_server
      hostname: keycloak
      restart: unless-stopped
      environment:
        - POSTGRES_DATABASE=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=keycloak
        - PROXY_ADDRESS_FORWARDING=true
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - POSTGRES_PORT_5432_TCP_ADDR=postgres
        - POSTGRES_PORT_5432_TCP_PORT=5432
#      links:
#        - keycloak_postgres:postgres
      ports:
        - "18080:8080"
      volumes:
        - ./volumes/keycloak_volume:/data
      restart: unless-stopped

volumes:
#  nginx_volume:
#    external: true
#  keycloak_volume:
#    external: true
  keycloak_postgresql_volume:
    external: true
#  letsencrypt_certificates:
#    external: true
#  letsencrypt_challenges:
#    external: true

