version: "2"

services:
  postgres:
      image: postgres:latest
      container_name: postgres
      restart: unless-stopped
      ports:
          - "15432:15432"
      environment:
          - POSTGRES_DB=keycloak
          - POSTGRES_USER=keycloak
          - POSTGRES_PASSWORD=keycloak
          - POSTGRES_ROOT_PASSWORD=keycloak
      volumes:
        - keycloak_postgresql_volume:/var/lib/postgresql/data
      restart: unless-stopped
  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      hostname: keycloak
      restart: unless-stopped
      environment:
      - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - KEYCLOAK_HTTP_PORT=80
        - KEYCLOAK_HTTP_PORT=443
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_PASSWORD=keycloak
        - POSTGRES_PORT_5432_TCP_ADDR=postgres
        - POSTGRES_PORT_5432_TCP_PORT=5432
      ports:
        - "80:80"
        - "443:443"
#        - "8080:8080"
#        - "8443:8443"
      volumes:
        - ./volumes/keycloak_volume:/data
        #- ./home/ubuntu/cognitive.syntelli.com:/etc/x509/https
        - letsencrypt_certificates:/etc/x509/https
      restart: unless-stopped

volumes:
#  nginx_volume:
#    external: true
#  keycloak_volume:
#    external: true
  keycloak_postgresql_volume:
    external: true
  letsencrypt_certificates:
    external: true
#  letsencrypt_challenges:
#    external: true

